name: Sample workflow bra1
on:
  issues:
    - created
    - opened
jobs:
  bra1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: misogihagi/lighthouse-ci-datadog-action
      - uses: ./
